from app.models import db, Comment


def seed_comments():
    seedArray = []

    seedArray.append(Comment(user_id = 1, course_id = 45, content = "I love this course!"))
    seedArray.append(Comment(user_id = 1, course_id = 71, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 3, course_id = 77, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 96, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 84, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 2, course_id = 81, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 3, course_id = 84, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 68, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 78, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 3, course_id = 93, content = "I like the music"))
    seedArray.append(Comment(user_id = 1, course_id = 97, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 1, course_id = 99, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 2, course_id = 88, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 6, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 16, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 78, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 1, course_id = 26, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 2, course_id = 39, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 3, course_id = 70, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 1, course_id = 31, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 3, course_id = 25, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 2, course_id = 92, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 48, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 65, content = "I love this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 8, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 3, course_id = 94, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 22, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 39, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 2, course_id = 29, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 1, course_id = 82, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 79, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 37, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "I like the music"))
    seedArray.append(Comment(user_id = 2, course_id = 10, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 3, course_id = 8, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 1, course_id = 49, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 38, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 40, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 1, course_id = 33, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 2, course_id = 37, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 1, course_id = 24, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 2, course_id = 50, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 2, course_id = 82, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 3, course_id = 46, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 2, course_id = 32, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 77, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 55, content = "I love this course!"))
    seedArray.append(Comment(user_id = 3, course_id = 43, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 1, course_id = 91, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 1, course_id = 58, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 3, course_id = 97, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 1, course_id = 56, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 1, course_id = 69, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 73, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 51, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 67, content = "I like the music"))
    seedArray.append(Comment(user_id = 3, course_id = 6, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 2, course_id = 41, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 2, course_id = 68, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 5, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 80, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 11, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 3, course_id = 54, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 2, course_id = 14, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 3, course_id = 40, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 1, course_id = 87, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 2, course_id = 60, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 2, course_id = 1, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 1, course_id = 10, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 34, content = "I love this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 20, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 1, course_id = 51, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 3, course_id = 89, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 3, course_id = 85, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 3, course_id = 17, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 1, course_id = 48, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 65, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 3, course_id = 70, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 81, content = "I like the music"))
    seedArray.append(Comment(user_id = 1, course_id = 13, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 2, course_id = 65, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 3, course_id = 49, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 26, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 91, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 86, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 3, course_id = 21, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 2, course_id = 26, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 2, course_id = 36, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 2, course_id = 42, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 1, course_id = 95, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 3, course_id = 93, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 46, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 14, content = "I love this course!"))
    seedArray.append(Comment(user_id = 1, course_id = 94, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 1, course_id = 91, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 93, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 83, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 2, course_id = 16, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 2, course_id = 6, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 12, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 3, course_id = 68, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 3, course_id = 96, content = "I like the music"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 3, course_id = 41, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 1, course_id = 27, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 48, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 94, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 1, course_id = 62, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 3, course_id = 36, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 1, course_id = 10, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 3, course_id = 9, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 3, course_id = 66, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 2, course_id = 69, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 2, course_id = 84, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 18, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 34, content = "I love this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 9, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 1, course_id = 34, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 3, course_id = 69, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 57, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 3, course_id = 3, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 1, course_id = 1, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 1, course_id = 37, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 11, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 97, content = "I like the music"))
    seedArray.append(Comment(user_id = 1, course_id = 77, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 1, course_id = 100, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 3, course_id = 9, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 98, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 6, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 1, course_id = 22, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 2, course_id = 82, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 3, course_id = 46, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 2, course_id = 15, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 1, course_id = 9, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 1, course_id = 51, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 1, course_id = 21, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 100, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 29, content = "I love this course!"))
    seedArray.append(Comment(user_id = 3, course_id = 13, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 3, course_id = 74, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 87, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 3, course_id = 4, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 2, course_id = 38, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 3, course_id = 42, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 51, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 36, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 60, content = "I like the music"))
    seedArray.append(Comment(user_id = 3, course_id = 32, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 2, course_id = 89, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 1, course_id = 49, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 71, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 90, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 66, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 2, course_id = 83, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 1, course_id = 3, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 1, course_id = 85, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 1, course_id = 85, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 1, course_id = 90, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 2, course_id = 99, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 1, course_id = 81, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 23, content = "I love this course!"))
    seedArray.append(Comment(user_id = 3, course_id = 62, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 2, course_id = 81, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 3, course_id = 64, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 2, course_id = 24, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 2, course_id = 3, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 3, course_id = 56, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 73, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 78, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 53, content = "I like the music"))
    seedArray.append(Comment(user_id = 2, course_id = 46, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 3, course_id = 37, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 3, course_id = 49, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 63, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 43, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 9, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 2, course_id = 56, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 1, course_id = 46, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 3, course_id = 5, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 3, course_id = 55, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 3, course_id = 39, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 36, content = "I love this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 11, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 3, course_id = 97, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 98, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 81, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 3, course_id = 81, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 3, course_id = 73, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 19, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 80, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 3, course_id = 68, content = "I like the music"))
    seedArray.append(Comment(user_id = 2, course_id = 98, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 2, course_id = 27, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 2, course_id = 83, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 4, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 81, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 1, course_id = 55, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 3, course_id = 34, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 3, course_id = 72, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 1, course_id = 41, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 1, course_id = 32, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 3, course_id = 31, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 1, course_id = 30, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 25, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 9, content = "I love this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 41, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 3, course_id = 89, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 99, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 28, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 1, course_id = 37, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 2, course_id = 27, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 95, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 56, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 93, content = "I like the music"))
    seedArray.append(Comment(user_id = 1, course_id = 54, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 2, course_id = 55, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 2, course_id = 22, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 25, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 96, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 3, course_id = 39, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 1, course_id = 31, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 1, course_id = 92, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 2, course_id = 70, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 1, course_id = 11, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 3, course_id = 88, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 3, course_id = 44, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 1, course_id = 50, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 55, content = "I love this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 42, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 2, course_id = 45, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 6, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 3, course_id = 93, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 1, course_id = 35, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 1, course_id = 91, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 1, course_id = 63, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 2, course_id = 94, content = "I like the music"))
    seedArray.append(Comment(user_id = 1, course_id = 56, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 3, course_id = 8, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 2, course_id = 15, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 1, course_id = 56, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 93, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 2, course_id = 18, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 1, course_id = 94, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 3, course_id = 62, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 3, course_id = 99, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 3, course_id = 49, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 1, course_id = 83, content = "The music is annoying"))
    seedArray.append(Comment(user_id = 2, course_id = 43, content = "My best friend and I met on this course"))
    seedArray.append(Comment(user_id = 3, course_id = 26, content = "I love this course!"))
    seedArray.append(Comment(user_id = 3, course_id = 38, content = "I HATE this course"))
    seedArray.append(Comment(user_id = 3, course_id = 30, content = "This course is sooo long"))
    seedArray.append(Comment(user_id = 2, course_id = 64, content = "Please help me, I'm stuck in a test project"))
    seedArray.append(Comment(user_id = 1, course_id = 21, content = "My friend is really good at this course"))
    seedArray.append(Comment(user_id = 1, course_id = 43, content = "I like this course's special feature"))
    seedArray.append(Comment(user_id = 1, course_id = 44, content = "I think this course's special feature is annoying"))
    seedArray.append(Comment(user_id = 3, course_id = 11, content = "This course is easy with (insert character)"))
    seedArray.append(Comment(user_id = 1, course_id = 84, content = "This course is pretty hard for (insert character)"))
    seedArray.append(Comment(user_id = 3, course_id = 90, content = "I like the music"))
    seedArray.append(Comment(user_id = 3, course_id = 100, content = "I like the game this is from"))
    seedArray.append(Comment(user_id = 2, course_id = 53, content = "How nostalgic!"))
    seedArray.append(Comment(user_id = 1, course_id = 5, content = "One time I got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 99, content = "One time I NEVER got a powerup on this course"))
    seedArray.append(Comment(user_id = 2, course_id = 22, content = "There's a secret easter egg on this course!"))
    seedArray.append(Comment(user_id = 2, course_id = 65, content = "Check out my best time, scrubs"))
    seedArray.append(Comment(user_id = 3, course_id = 88, content = "I broke my controller here"))
    seedArray.append(Comment(user_id = 3, course_id = 93, content = "I hated this obstacle"))
    seedArray.append(Comment(user_id = 1, course_id = 99, content = "My partner and I broke up after this race"))
    seedArray.append(Comment(user_id = 3, course_id = 91, content = "This track drove me to drink"))
    seedArray.append(Comment(user_id = 2, course_id = 11, content = "I beat my kid at this course and they started crying"))
    seedArray.append(Comment(user_id = 1, course_id = 36, content = "The music is annoying"))



    for item in seedArray:
        db.session.add(item)

    db.session.commit()