from app.models import db, Game


def seed_games():
    seedArray = []

    seedArray.append(Game(name="Super Mario Kart", description="Super Mario Kart was the first entry in the series, released for the SNES in 1992. The game has a total of eight playable characters who, when computer-controlled, use special power-up items specific to each character (such as eggs for Yoshi). The twenty tracks in this game, based on locations in Super Mario World (such as Donut Plains), are all short in length compared to other tracks in the series; thus, they are raced in five laps instead of the usual three. All player-characters featured here have reappeared in all later entries in the series, except for Koopa Troopa who has only returned intermittently, and Donkey Kong Jr. who would never again be used in the series except for the much later Mario Kart Tour's 'Super Mario Kart Tour', which features his and Mario's respective 16-bit sprite work. Unlike other games in the series, Super Mario Kart allows players only a limited number of lives, which are lost whenever a racer loses and is 'ranked out'. A notable aspect of the game's presentation is its use of the SNES's Mode 7 graphics technology, which allows for free rotation and scaling of planes to give a three-dimensional appearance. ", splash_img="https://mario.wiki.gallery/images/7/72/SMK_NA_Box_Cover.jpg"))
    seedArray.append(Game(name="Mario Kart 64", description="Mario Kart 64, launched in 1996/1997 for the Nintendo 64, was a vast improvement from the SNES original. It moved the series to polygon-based true 3D computer graphics for track design, allowing for track features that were not possible with Mode 7, such as bridges, walls, pits, and elevation changes; however, the characters and items remain 2D pre-rendered sprites. Other new additions include digital voice acting, 4-player support, the modern character weight classification system, Mirror mode, ghost data for Time Trial courses, and new items, including the Spiny Shell (which targets and attacks the player in the lead), the Fake Item Box, multiples of existing items, and the Super Mushroom. The game features 16 normal race courses, as well as four battle courses. Though there are still eight playable characters, two new characters are introduced: Wario (replacing Koopa Troopa) and Donkey Kong (replacing Donkey Kong Jr.), both of whom have reappeared throughout the series. ", splash_img="https://mario.wiki.gallery/images/5/5f/MK64_Cover.png"))
    seedArray.append(Game(name="Mario Kart: Double Dash!!", description="Mario Kart: Double Dash!!, released in 2003 for the Nintendo GameCube, introduced a number of new gameplay features. The most prominent feature is co-op gameplay with two riders per kart, where one player drives and the other uses items. This is also the first game to allow everyone to move on regardless of which position they earned after each race. In addition to 9 of the 10 characters who return from previous installments (excluding Donkey Kong Jr.), 11 new playable characters are added: Diddy Kong, Bowser Jr., Birdo, Princess Daisy, Waluigi, Koopa Paratroopa, Baby Mario, Baby Luigi, Petey Piranha, King Boo, and the newly-created Toadette. Each pair of drivers is assigned their own unique special item (e.g. fireballs for Mario and Luigi, or giant bananas for Donkey and Diddy Kong). Individual characters also gain their own unique custom-designed karts. Another new addition is the 'All-Cup Tour,' which has the player race in every track at the same time; once this is cleared on the highest difficulty setting, the player can unlock a 'Parade Kart,' which can be used by any character of any weight. ", splash_img="https://mario.wiki.gallery/images/7/70/Mario_Kart_Double_Dash%21%21.jpg"))
    seedArray.append(Game(name="Mario Kart Wii", description="Mario Kart Wii was released for the Wii in 2008. For the first time in the series, the player can race using motorcycles (labeled in-game as 'bikes') and perform tricks while driving that produce speed boosts, such as mid-air stunts, slipstreaming, and wheelies. The game is primarily played using the plastic Wii Wheel accessory, which uses the controller's motion sensing to simulate operating a steering wheel. The game features 24 playable characters, the largest roster of the series at the time (Baby Daisy makes her debut in the Mario franchise, and other new additions to the Mario Kart series include Baby Peach, Funky Kong, Dry Bowser, and Rosalina; Mii characters saved in the console's Mii Channel are also playable). The POW Block, Mega Mushroom, and Thunder Cloud make their first and only main series Mario Kart appearance as usable items in this game. The concept of retro tracks is expanded to the Battle mode, with one retro battle course from each game in the series. When Nintendo Wi-Fi Connection was in existence, Mario Kart Wii allowed the VS and Battle modes to be played by up to twelve participants, and also featured the 'Mario Kart Channel,' which was available as an optionally selectable channel on the Wii Menu and allowed players to check their regional or global Time Trial rankings, send and receive ghost data, and participate in worldwide tournaments on modified courses with special objectives. ", splash_img="https://mario.wiki.gallery/images/2/29/Mkwii.jpg"))
    seedArray.append(Game(name="Mario Kart 7", description="Mario Kart 7, released in 2011 for the Nintendo 3DS, features optional 3D stereoscopic graphics and can be played using the console's gyroscope, which allows players to race in first-person and steer vehicles simply by turning the game system. Other features unseen in previous installments include the ability to build customizable vehicles with unlockable parts such as frames or tires; retractable hang gliders, which allow players to glide through the air, skipping over parts of the track or locating new routes/shortcuts that are otherwise inaccessible; fully submersible karts; and segments of tracks that are completely underwater. The game features 4 new characters: Metal Mario, Lakitu, Wiggler, and Honey Queen. This is also the first Mario Kart game where Shy Guy can be played as without playing in multiplayer mode. The player can play online via Nintendo Network, participating in races or battles with up to seven other players, and exchange game data with other Nintendo 3DS consoles. Two of the new courses are set on Wuhu Island from the non-Mario game series Wii Fit. ", splash_img="https://mario.wiki.gallery/images/5/5e/Mario-Kart-7-Box-Art.jpg"))
    seedArray.append(Game(name="Mario Kart 8", description="Mario Kart 8, released for the Wii U in 2014, introduces anti-gravity sections that allow players to drive on walls and ceilings, allowing for more alternate paths in courses. In these sections, a player can bump into other racers or special bumpers to trigger a Spin Boost, which gives them an extra speed boost. The game also introduces all-terrain vehicles (ATVs), allows the player to view replay data from others and upload highlights to YouTube via 'Mario Kart TV', introduces the Koopalings as new playable characters, and allows up to four people to play in Grand Prix races. Baby Rosalina and Pink Gold Peach are also introduced as new characters to the Mario franchise. Additional characters, vehicles, and tracks have been released as downloadable content, including actual Mercedes-Benz vehicles. Characters that have been released as add-on content include Tanooki Mario, Cat Peach, the returning Dry Bowser, Link from The Legend of Zelda, and the Villager and Isabelle from Animal Crossing; tracks themed after various non-Mario game series have also been made available as add-on content. Additionally, Mario Kart 8 is notable for being the first game in the series to boast HD graphics and live-orchestrated music, as well as the first to receive post-release updates adding new features and enhancements, including rearranged post-race options, 200cc, and support for Nintendo's amiibo line of figurines. The year it was released, a browser game on Play Nintendo called Mario Kart 8 Party Starter was made based on the game. ", splash_img="https://mario.wiki.gallery/images/thumb/a/ad/MK8_NA_Box_Art.jpg/1200px-MK8_NA_Box_Art.jpg"))

    for item in seedArray:
        db.session.add(item)

    db.session.commit()
