from app.models import db, Record


def seed_records():
    seedArray = []

    seedArray.append(Record(user_id = 3, course_id = 71, time = 577187, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 97, time = 384541, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 93, time = 341716, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 97, time = 393931, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 21, time = 350104, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 54, time = 342896, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 68, time = 399419, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 16, time = 571932, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 1, time = 514075, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 46, time = 712314, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 72, time = 349058, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 33, time = 405918, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 50, time = 545564, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 92, time = 494065, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 77, time = 185180, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 68, time = 617012, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 21, time = 335848, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 283137, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 48, time = 225965, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 19, time = 646771, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 52, time = 341094, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 61, time = 314675, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 65, time = 477946, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 50, time = 717892, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 3, time = 383895, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 3, time = 400047, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 44, time = 194025, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 25, time = 385719, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 54, time = 386902, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 27, time = 683575, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 19, time = 547254, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 78, time = 583974, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 78, time = 218297, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 39, time = 270490, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 69, time = 643829, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 39, time = 625293, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 89, time = 513828, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 25, time = 366001, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 10, time = 601344, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 6, time = 510925, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 57, time = 453168, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 60, time = 707835, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 24, time = 381799, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 63, time = 695522, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 87, time = 458198, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 4, time = 194776, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 20, time = 590217, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 29, time = 296076, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 5, time = 374214, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 82, time = 347623, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 96, time = 236690, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 73, time = 615689, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 51, time = 199038, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 15, time = 559327, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 44, time = 298249, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 44, time = 245893, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 8, time = 224249, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 92, time = 662793, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 61, time = 440773, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 52, time = 280654, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 81, time = 605492, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 2, time = 643230, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 51, time = 296750, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 43, time = 565406, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 100, time = 566668, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 54, time = 352158, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 75, time = 374818, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 16, time = 370939, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 75, time = 241798, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 67, time = 604455, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 40, time = 570257, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 46, time = 602313, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 10, time = 200181, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 96, time = 604897, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 32, time = 323980, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 98, time = 291243, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 76, time = 592696, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 28, time = 510629, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 99, time = 230553, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 38, time = 423238, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 1, time = 212211, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 57, time = 280089, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 434324, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 97, time = 233309, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 14, time = 230117, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 36, time = 459441, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 74, time = 273663, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 71, time = 679212, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 17, time = 560935, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 85, time = 267925, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 374546, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 42, time = 425297, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 17, time = 541445, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 14, time = 202197, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 46, time = 486231, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 90, time = 709543, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 56, time = 501204, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 67, time = 274385, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 70, time = 450589, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 70, time = 469951, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 40, time = 375688, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 81, time = 446634, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 63, time = 383622, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 29, time = 503994, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 27, time = 286069, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 22, time = 233612, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 33, time = 432513, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 49, time = 328540, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 84, time = 351574, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 25, time = 563985, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 77, time = 201972, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 66, time = 642187, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 91, time = 581837, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 83, time = 200716, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 12, time = 408986, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 15, time = 386405, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 20, time = 640988, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 66, time = 690304, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 17, time = 306402, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 94, time = 585238, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 82, time = 521972, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 57, time = 282991, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 10, time = 236481, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 87, time = 274994, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 99, time = 220780, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 96, time = 537255, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 83, time = 290206, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 60, time = 233582, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 32, time = 595178, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 58, time = 697286, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 1, time = 335664, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 100, time = 555221, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 47, time = 198683, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 79, time = 517698, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 79, time = 249136, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 7, time = 697482, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 22, time = 705311, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 86, time = 200707, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 100, time = 301838, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 63, time = 345958, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 43, time = 329656, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 99, time = 489692, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 93, time = 619217, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 71, time = 340778, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 78, time = 257020, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 7, time = 376418, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 87, time = 592732, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 46, time = 368894, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 34, time = 528367, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 35, time = 479197, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 25, time = 442935, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 11, time = 494225, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 15, time = 201245, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 80, time = 675959, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 16, time = 689686, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 28, time = 269946, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 41, time = 482003, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 78, time = 230714, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 84, time = 457086, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 96, time = 266758, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 58, time = 193522, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 70, time = 345490, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 88, time = 540558, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 48, time = 292922, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 30, time = 409282, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 8, time = 522973, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 6, time = 388965, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 35, time = 284349, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 56, time = 391872, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 59, time = 225886, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 43, time = 250078, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 47, time = 607463, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 78, time = 367106, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 57, time = 672201, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 23, time = 583662, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 69, time = 603152, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 63, time = 655840, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 23, time = 707767, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 56, time = 212090, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 35, time = 434868, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 19, time = 661556, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 89, time = 501568, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 22, time = 648998, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 26, time = 439799, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 73, time = 568118, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 64, time = 609756, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 27, time = 704120, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 87, time = 527760, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 17, time = 433987, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 71, time = 417681, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 46, time = 395437, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 33, time = 474069, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 83, time = 402331, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 17, time = 241295, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 59, time = 411379, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 80, time = 347576, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 21, time = 599638, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 52, time = 627686, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 95, time = 527457, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 74, time = 687314, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 98, time = 506949, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 76, time = 219151, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 21, time = 591638, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 67, time = 418832, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 74, time = 533056, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 93, time = 476439, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 96, time = 712876, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 96, time = 635562, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 46, time = 487732, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 58, time = 602687, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 63, time = 622536, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 15, time = 404051, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 20, time = 522398, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 37, time = 427828, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 36, time = 641099, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 63, time = 386751, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 12, time = 607007, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 2, time = 713770, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 648029, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 17, time = 390378, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 65, time = 299955, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 9, time = 676790, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 35, time = 215820, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 26, time = 268632, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 72, time = 446784, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 89, time = 602516, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 42, time = 410778, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 76, time = 415536, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 3, time = 534359, character = "Bowser"))
    seedArray.append(Record(user_id = 2, course_id = 57, time = 375758, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 16, time = 462043, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 82, time = 187629, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 9, time = 381073, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 391882, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 92, time = 620531, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 75, time = 531872, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 8, time = 494959, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 57, time = 684182, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 96, time = 307630, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 49, time = 261933, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 18, time = 533294, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 18, time = 190135, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 84, time = 215327, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 83, time = 253383, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 29, time = 222691, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 98, time = 413327, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 83, time = 215783, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 58, time = 378847, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 52, time = 308199, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 88, time = 312700, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 91, time = 487408, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 89, time = 534243, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 93, time = 621109, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 25, time = 367057, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 77, time = 592189, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 59, time = 495286, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 46, time = 259364, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 1, time = 630888, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 55, time = 261383, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 19, time = 456257, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 84, time = 671399, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 95, time = 187941, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 89, time = 461046, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 566917, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 91, time = 405971, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 32, time = 220613, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 8, time = 428767, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 74, time = 343036, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 32, time = 654334, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 2, time = 713819, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 91, time = 466484, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 75, time = 332122, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 17, time = 328803, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 82, time = 258501, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 63, time = 531265, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 40, time = 577082, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 61, time = 613849, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 93, time = 548726, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 589431, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 49, time = 516180, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 11, time = 637381, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 30, time = 232850, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 51, time = 696695, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 95, time = 638916, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 31, time = 547550, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 95, time = 257274, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 84, time = 362407, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 28, time = 560733, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 95, time = 291799, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 11, time = 618960, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 44, time = 456266, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 53, time = 324712, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 88, time = 580998, character = "Bowser"))
    seedArray.append(Record(user_id = 2, course_id = 29, time = 203583, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 100, time = 398853, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 81, time = 222388, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 16, time = 197011, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 93, time = 632107, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 97, time = 524408, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 15, time = 452683, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 72, time = 227877, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 86, time = 373488, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 32, time = 497309, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 75, time = 182871, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 21, time = 478957, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 65, time = 450504, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 12, time = 266203, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 62, time = 580878, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 95, time = 543324, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 29, time = 438566, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 100, time = 521310, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 85, time = 365830, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 15, time = 335260, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 61, time = 492008, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 69, time = 409268, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 16, time = 395473, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 79, time = 710808, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 92, time = 685133, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 6, time = 265307, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 34, time = 224659, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 81, time = 208368, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 4, time = 442412, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 26, time = 489888, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 20, time = 226992, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 49, time = 657420, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 43, time = 651317, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 77, time = 282749, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 61, time = 409332, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 87, time = 307097, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 87, time = 238394, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 77, time = 260035, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 21, time = 392102, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 45, time = 336463, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 67, time = 194873, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 58, time = 403389, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 62, time = 503347, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 60, time = 714271, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 2, time = 661388, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 95, time = 642437, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 79, time = 337544, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 4, time = 193465, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 27, time = 519146, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 67, time = 490797, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 57, time = 529834, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 15, time = 498947, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 82, time = 397205, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 75, time = 192009, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 81, time = 242174, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 69, time = 394314, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 60, time = 253929, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 69, time = 603919, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 339976, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 15, time = 616024, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 73, time = 334496, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 69, time = 230818, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 38, time = 385236, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 14, time = 670097, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 21, time = 662194, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 9, time = 195790, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 96, time = 185029, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 49, time = 350045, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 55, time = 536428, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 59, time = 546259, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 64, time = 606075, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 21, time = 549210, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 23, time = 652821, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 60, time = 406094, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 81, time = 487243, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 87, time = 587985, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 60, time = 471114, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 83, time = 650821, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 70, time = 589870, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 21, time = 592055, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 83, time = 643817, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 82, time = 367171, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 65, time = 441224, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 52, time = 594153, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 560539, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 37, time = 512810, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 485619, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 7, time = 346299, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 81, time = 707795, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 4, time = 519190, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 49, time = 483563, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 77, time = 414023, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 52, time = 257685, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 23, time = 436330, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 87, time = 583467, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 17, time = 225342, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 16, time = 496836, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 34, time = 577099, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 57, time = 401429, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 16, time = 638851, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 64, time = 207713, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 55, time = 322513, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 46, time = 716537, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 64, time = 516488, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 76, time = 644525, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 17, time = 314098, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 34, time = 367538, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 95, time = 258614, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 94, time = 397269, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 49, time = 528323, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 41, time = 455819, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 34, time = 350845, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 52, time = 223238, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 54, time = 506062, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 62, time = 578241, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 83, time = 480504, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 61, time = 324603, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 81, time = 529155, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 10, time = 532940, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 40, time = 691225, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 55, time = 265696, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 72, time = 216262, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 29, time = 688991, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 6, time = 606463, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 23, time = 206931, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 35, time = 417695, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 33, time = 620492, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 79, time = 285653, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 1, time = 409950, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 13, time = 682503, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 66, time = 204545, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 98, time = 700955, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 87, time = 515182, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 50, time = 198581, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 35, time = 271386, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 13, time = 645132, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 15, time = 417948, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 40, time = 565842, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 25, time = 684921, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 41, time = 325740, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 50, time = 438575, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 29, time = 624595, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 60, time = 424915, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 26, time = 426079, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 88, time = 363680, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 62, time = 347171, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 26, time = 199398, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 98, time = 696491, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 73, time = 407354, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 1, time = 699937, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 13, time = 188449, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 44, time = 543711, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 44, time = 717232, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 20, time = 473604, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 43, time = 674440, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 19, time = 247278, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 6, time = 496454, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 87, time = 575471, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 77, time = 701435, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 14, time = 226108, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 73, time = 460298, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 43, time = 443308, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 438150, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 84, time = 547838, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 25, time = 549569, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 4, time = 443089, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 3, time = 591892, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 53, time = 226699, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 80, time = 428558, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 24, time = 377137, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 37, time = 713943, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 58, time = 412437, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 78, time = 266928, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 58, time = 268860, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 67, time = 529123, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 69, time = 407490, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 80, time = 309405, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 56, time = 694276, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 100, time = 256246, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 41, time = 439853, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 73, time = 506451, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 581190, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 98, time = 635084, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 5, time = 678686, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 22, time = 638222, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 55, time = 633527, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 29, time = 670171, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 83, time = 580851, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 26, time = 385735, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 17, time = 369582, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 4, time = 463322, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 80, time = 290753, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 53, time = 187318, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 31, time = 556151, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 42, time = 566226, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 87, time = 658043, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 513500, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 2, time = 423162, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 41, time = 341678, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 62, time = 339659, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 51, time = 580804, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 53, time = 410774, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 12, time = 208227, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 15, time = 310721, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 84, time = 404347, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 98, time = 497278, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 37, time = 213490, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 59, time = 668397, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 33, time = 671350, character = "Wario"))
    seedArray.append(Record(user_id = 2, course_id = 91, time = 334118, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 28, time = 479419, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 70, time = 673513, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 97, time = 323635, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 1, time = 524088, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 78, time = 388770, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 92, time = 619839, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 93, time = 527409, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 48, time = 456007, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 48, time = 673494, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 88, time = 612776, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 22, time = 185798, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 100, time = 617409, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 36, time = 393336, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 16, time = 706784, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 31, time = 419748, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 58, time = 381851, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 82, time = 431449, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 98, time = 509816, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 61, time = 570538, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 28, time = 202877, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 77, time = 235284, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 72, time = 255194, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 28, time = 481531, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 79, time = 247102, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 71, time = 472900, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 52, time = 291732, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 39, time = 505561, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 37, time = 545235, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 98, time = 333168, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 29, time = 553054, character = "Bowser"))
    seedArray.append(Record(user_id = 2, course_id = 82, time = 292771, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 9, time = 569961, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 11, time = 255317, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 23, time = 623312, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 71, time = 710737, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 62, time = 629724, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 2, time = 310507, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 88, time = 321363, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 93, time = 516412, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 77, time = 655837, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 1, time = 701809, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 86, time = 652012, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 13, time = 345681, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 6, time = 686215, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 19, time = 288297, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 31, time = 213126, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 100, time = 673775, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 59, time = 706142, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 58, time = 603184, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 48, time = 695035, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 48, time = 631161, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 94, time = 382937, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 86, time = 295628, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 3, time = 670847, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 56, time = 596933, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 89, time = 212754, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 40, time = 416529, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 92, time = 459706, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 1, time = 606495, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 14, time = 320636, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 89, time = 245250, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 95, time = 349722, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 50, time = 317162, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 37, time = 247956, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 44, time = 188498, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 296465, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 19, time = 232613, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 9, time = 712647, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 88, time = 421998, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 2, time = 196470, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 67, time = 352477, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 57, time = 610373, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 40, time = 531543, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 85, time = 291080, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 74, time = 589984, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 88, time = 328779, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 63, time = 600516, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 38, time = 448103, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 94, time = 584373, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 100, time = 331164, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 72, time = 313993, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 60, time = 415326, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 77, time = 243967, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 94, time = 301148, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 48, time = 542384, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 88, time = 682428, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 55, time = 645019, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 11, time = 702705, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 62, time = 652085, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 74, time = 326180, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 77, time = 496521, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 15, time = 362361, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 38, time = 621794, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 35, time = 686836, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 36, time = 271276, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 717716, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 57, time = 240390, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 3, course_id = 26, time = 644092, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 46, time = 491929, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 544605, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 95, time = 625073, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 23, time = 362396, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 60, time = 407084, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 25, time = 295769, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 64, time = 509942, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 87, time = 470797, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 4, time = 708934, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 7, time = 549568, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 42, time = 468909, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 35, time = 599226, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 67, time = 339205, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 358042, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 95, time = 694617, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 25, time = 395721, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 33, time = 424115, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 66, time = 263884, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 69, time = 384960, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 12, time = 198558, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 20, time = 552559, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 84, time = 501592, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 54, time = 689648, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 69, time = 524829, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 20, time = 539968, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 34, time = 421075, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 28, time = 267603, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 6, time = 478732, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 40, time = 537031, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 48, time = 372409, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 25, time = 575069, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 30, time = 521723, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 204549, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 45, time = 592630, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 4, time = 485956, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 56, time = 304052, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 27, time = 618852, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 63, time = 532475, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 26, time = 694391, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 36, time = 656492, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 73, time = 678036, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 68, time = 357799, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 23, time = 265410, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 60, time = 570888, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 34, time = 711863, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 69, time = 188180, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 1, time = 607185, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 100, time = 526000, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 629005, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 30, time = 695728, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 78, time = 605225, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 65, time = 232717, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 94, time = 504499, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 13, time = 236325, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 35, time = 638531, character = "Baby Mario"))
    seedArray.append(Record(user_id = 2, course_id = 78, time = 616562, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 11, time = 484518, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 26, time = 555054, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 68, time = 666664, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 436663, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 7, time = 515620, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 8, time = 516513, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 71, time = 601922, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 36, time = 660244, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 56, time = 386221, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 45, time = 676539, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 320592, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 36, time = 670861, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 44, time = 211911, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 5, time = 430367, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 2, time = 617651, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 71, time = 287091, character = "Mario"))
    seedArray.append(Record(user_id = 1, course_id = 99, time = 301511, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 91, time = 680235, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 11, time = 280039, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 1, time = 260246, character = "Bowser"))
    seedArray.append(Record(user_id = 1, course_id = 32, time = 477650, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 89, time = 458713, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 1, time = 449547, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 2, time = 543142, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 70, time = 325657, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 583485, character = "Birdo"))
    seedArray.append(Record(user_id = 1, course_id = 4, time = 237088, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 32, time = 352445, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 50, time = 460110, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 100, time = 652834, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 58, time = 441627, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 43, time = 595640, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 59, time = 621437, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 29, time = 679750, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 4, time = 240398, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 26, time = 265249, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 11, time = 325825, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 2, time = 661465, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 29, time = 275464, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 57, time = 533055, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 7, time = 187011, character = "Yoshi"))
    seedArray.append(Record(user_id = 3, course_id = 68, time = 425575, character = "Birdo"))
    seedArray.append(Record(user_id = 2, course_id = 47, time = 370630, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 5, time = 564511, character = "Koopa"))
    seedArray.append(Record(user_id = 2, course_id = 53, time = 399378, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 21, time = 603356, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 83, time = 569244, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 32, time = 628632, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 90, time = 428049, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 45, time = 525058, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 18, time = 484449, character = "Peach"))
    seedArray.append(Record(user_id = 1, course_id = 10, time = 542544, character = "Bowser"))
    seedArray.append(Record(user_id = 2, course_id = 36, time = 497803, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 91, time = 648196, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 58, time = 534640, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 56, time = 550206, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 82, time = 367834, character = "Yoshi"))
    seedArray.append(Record(user_id = 2, course_id = 36, time = 522621, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 54, time = 402747, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 16, time = 444543, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 97, time = 361607, character = "Shy Guy"))
    seedArray.append(Record(user_id = 2, course_id = 33, time = 427442, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 638584, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 22, time = 538502, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 75, time = 223443, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 81, time = 474860, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 81, time = 605495, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 50, time = 256832, character = "Bowser"))
    seedArray.append(Record(user_id = 2, course_id = 72, time = 215056, character = "Wario"))
    seedArray.append(Record(user_id = 1, course_id = 42, time = 220264, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 3, course_id = 11, time = 361127, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 44, time = 229524, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 2, time = 553193, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 80, time = 421958, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 8, time = 362440, character = "Waluigi"))
    seedArray.append(Record(user_id = 3, course_id = 91, time = 475420, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 32, time = 406232, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 68, time = 519326, character = "Dry Bones"))
    seedArray.append(Record(user_id = 2, course_id = 2, time = 363713, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 84, time = 642070, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 62, time = 313026, character = "Luigi"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 534533, character = "Toad"))
    seedArray.append(Record(user_id = 3, course_id = 99, time = 199947, character = "Peach"))
    seedArray.append(Record(user_id = 3, course_id = 36, time = 302580, character = "Bowser"))
    seedArray.append(Record(user_id = 2, course_id = 36, time = 495229, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 33, time = 472061, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 1, course_id = 9, time = 684095, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 2, course_id = 15, time = 192450, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 2, course_id = 41, time = 437547, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 55, time = 320665, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 72, time = 412825, character = "Waluigi"))
    seedArray.append(Record(user_id = 1, course_id = 52, time = 547840, character = "Koopa"))
    seedArray.append(Record(user_id = 3, course_id = 96, time = 632287, character = "Shy Guy"))
    seedArray.append(Record(user_id = 3, course_id = 97, time = 353451, character = "Dry Bones"))
    seedArray.append(Record(user_id = 1, course_id = 19, time = 306151, character = "Baby Mario"))
    seedArray.append(Record(user_id = 1, course_id = 17, time = 619792, character = "Mario"))
    seedArray.append(Record(user_id = 2, course_id = 23, time = 562048, character = "Luigi"))
    seedArray.append(Record(user_id = 3, course_id = 74, time = 185571, character = "Toad"))
    seedArray.append(Record(user_id = 2, course_id = 56, time = 503174, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 70, time = 528528, character = "Bowser"))
    seedArray.append(Record(user_id = 3, course_id = 87, time = 297798, character = "Wario"))
    seedArray.append(Record(user_id = 3, course_id = 10, time = 237336, character = "Donkey Kong"))
    seedArray.append(Record(user_id = 2, course_id = 27, time = 468969, character = "Donkey Kong Jr"))
    seedArray.append(Record(user_id = 1, course_id = 2, time = 592993, character = "Bowser Jr"))
    seedArray.append(Record(user_id = 3, course_id = 52, time = 460559, character = "Yoshi"))
    seedArray.append(Record(user_id = 1, course_id = 59, time = 718847, character = "Birdo"))
    seedArray.append(Record(user_id = 3, course_id = 32, time = 408546, character = "Waluigi"))
    seedArray.append(Record(user_id = 2, course_id = 16, time = 389723, character = "Koopa"))
    seedArray.append(Record(user_id = 1, course_id = 51, time = 661841, character = "Shy Guy"))
    seedArray.append(Record(user_id = 1, course_id = 56, time = 268793, character = "Dry Bones"))
    seedArray.append(Record(user_id = 3, course_id = 43, time = 554805, character = "Baby Mario"))
    seedArray.append(Record(user_id = 3, course_id = 1, time = 314714, character = "Mario"))
    seedArray.append(Record(user_id = 3, course_id = 67, time = 660586, character = "Luigi"))
    seedArray.append(Record(user_id = 2, course_id = 72, time = 405982, character = "Toad"))
    seedArray.append(Record(user_id = 1, course_id = 72, time = 508496, character = "Peach"))
    seedArray.append(Record(user_id = 2, course_id = 59, time = 714735, character = "Bowser"))



    for item in seedArray:
        db.session.add(item)

    db.session.commit()
